### ISSUE TITLE
toArray() uses the id attribute hardcoded to get parentItem

### ISSUE THREAD

**Issue by Avaq** [mjsarfatti/nestedSortable#3]
on line 271 is the following code: 

$(item).parent(o.listType).parent('li').attr('id')

It grabs the id from the parent item, however the id doesn't always have to be inside the HTML id attribute (as taken into account when selecting the item id on line 266):

$(item).attr(o.attribute || 'id')

In order for users to pass their own attribute without getting a "can not call match() on undefined" error the piece of code on line 271 that I showed needs to change to:

$(item).parent(o.listType).parent('li').attr(o.attribute || 'id')

**Comment by Avaq** [comment]
Closed: New version already fixed this. My mistake.

**Comment by mjsarfatti** [comment]
Are you sure you are using the latest version?

**Comment by Avaq** [comment]
I see now :) The version having the latest commit with improvements is not available on your website, from which I downloaded the source: http://mjsarfatti.com/sandbox/nestedSortable/jquery.ui.nestedSortable.js

**Comment by mjsarfatti** [comment]
uhm i guess i forgot to update that months ago... thanks for the heads up!

**Comment by promehdioh** [comment]
I use nestedsortable.js in a cms project with codeigniter framework (tutsplus course)
the list drag and drop has worked but when I click on save button for ajax request with jquery I received an error message : Uncaught TypeError: Cannot call method 'match' of undefined 
I think that the problem is from toArray function but I don't have solution 
this is the request code
$(document).ready(function(){
        $.post('<?=base_url("index.php/admin/pages/order_ajax"); ?>',{},function(data){
            $('#orderResult').html(data);
        });
        $('#save').click(function(){
            $('.sortable').nestedSortable("toArray");
        });
    });
Help me please
