### ISSUE TITLE
isAllowed option question

### ISSUE THREAD

**Issue by benlwilliams** [mjsarfatti/nestedSortable#50]
In the documentation the `isAllowed` function has parameters of `item` and `parent`.  I can't tell if `parent` means the new parent item that I'm trying to move the item under, or if it is the parent that the item originally originated from.

**Comment by mjsarfatti** [comment]
It's the parent of the placeholder. And the 'item' is in fact the
placeholder.

2012/9/6 Ben Williams notifications@github.com

**Comment by benlwilliams** [comment]
@mjsarfatti - thanks.

**Comment by benlwilliams** [comment]
@mjsarfatti - I was hoping you could give me a use case for the isAllowed function.  The only way I could see this being useful is if `item` is the actual item being dragged, and not the placeholder of where the item is going.

**Comment by nreynis** [comment]
@blw0010 this is the most reported issue, everyone is complaining about it.
The API is misdesigned and will be (I hope) fixed in a future release.

In the meantime you can use this line of code in your callback to address this shortcoming :
var item = ($('#list-container').data().nestedSortable.currentItem);

**Comment by benlwilliams** [comment]
@ywg Ok thank you.  I ended up doing a workaround on the mousedown even when clicking a list item. I determined at the mousedown even what nesting would not be allowed on which elements and applied the disableNesting class to those items. On mouseup I removed all the disableNesting classes.
