### ISSUE TITLE
Question about "toArray" method

### ISSUE THREAD

**Issue by benoitboucart** [mjsarfatti/nestedSortable#61]
Hi

First of all, thanks for your great plugin!

The toArray method has a problem.

Only the first item receive the depth of 0 (but there are many others with a depth of 0). I've tested it on my own items, and I have the same problem.

`l
        '0' ...
        'item_id' ...
        'parent_id' => "none"
        'depth' => "0"
        'left' => "1"
        'right' => "22"
`
see demo: http://mjsarfatti.com/sandbox/nestedSortable/

**Comment by mjsarfatti** [comment]
Hi,
you will use the toArray method only if you implement the nested set model (see the links in the README file). In that case you will have _n_ root elements in your list, but in order to comply with the nested set model you still need one super-root element: the first ancestor of every other item. That's what the first item of the toArray is, not an actual HTML element.

**Comment by benoitboucart** [comment]
Ok, my bad, thanks for the info!
